# This file is part of QOBLIB - Quantum Optimization Benchmarking Library
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "check"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "check_portfolio"
path = "src/main.rs"

[dependencies]
flate2 = "1.0"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"

[profile.release]
overflow-checks = true
